import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("keeps the required Slivadoc Partners content", async () => {
  const html = await readFile(new URL("../app/partner-portal.tsx", import.meta.url), "utf8");
  const categoryForm = await readFile(new URL("../app/kemitraan/partnership-form.tsx", import.meta.url), "utf8");
  const categoryPage = await readFile(new URL("../app/kemitraan/[slug]/page.tsx", import.meta.url), "utf8");
  const categoryConfig = await readFile(new URL("../app/partnership-categories.ts", import.meta.url), "utf8");
  const keywordMap = await readFile(new URL("../seo/partnership-keywords.csv", import.meta.url), "utf8");
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  const manifest = await readFile(new URL("../app/manifest.ts", import.meta.url), "utf8");
  const svgFavicon = await readFile(new URL("../public/favicon.svg", import.meta.url), "utf8");
  const robots = await readFile(new URL("../app/robots.ts", import.meta.url), "utf8");
  const sitemap = await readFile(new URL("../app/sitemap.ts", import.meta.url), "utf8");
  const analytics = await readFile(new URL("../app/google-analytics.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const warehouseAsset = await readFile(new URL("../public/brand/slivadoc-warehouse.webp", import.meta.url));
  const ecosystemHeroAsset = await readFile(new URL("../public/brand/slivadoc-ecosystem-hero.webp", import.meta.url));
  const partnerLogoAssets = await Promise.all([
    "lion-parcel.svg",
    "jne.svg",
    "jnt-cargo.svg",
    "sicepat.svg",
    "idexpress.svg",
    "batpay.webp",
    "ocbc.png",
    "cimb.svg",
    "mandiri.png",
  ].map((name) => readFile(new URL(`../public/partners/${name}`, import.meta.url))));

  assert.match(layout, /Slivadoc Partners: Aplikasi POS Petshop & Klinik Hewan Gratis/);
  assert.match(layout, /metadataBase: new URL\(siteUrl\)/);
  assert.match(layout, /canonical: "\/"/);
  assert.doesNotMatch(layout, /keywords: seoKeywords/);
  assert.match(layout, /summary_large_image/);
  assert.match(layout, /slivadoc-ecosystem-hero\.webp/);
  const keywords = keywordMap.trim().split("\n").slice(1).map((line) => line.split('","')[0].slice(1));
  assert.equal(keywords.length, 1000);
  assert.equal(new Set(keywords).size, 1000);
  assert.ok(keywords.includes("daftar mitra petshop Slivadoc"));
  assert.match(categoryConfig, /slug: "petshop"/);
  assert.equal((categoryConfig.match(/slug: "/g) || []).length, 18);
  assert.match(categoryPage, /generateStaticParams/);
  assert.match(categoryPage, /canonical: path/);
  assert.match(categoryPage, /PartnershipForm category=\{category\}/);
  assert.match(layout, /"@type": "SoftwareApplication"/);
  assert.match(robots, /partners\.slivadoc\.com\/sitemap\.xml/);
  assert.match(sitemap, /https:\/\/partners\.slivadoc\.com/);
  assert.match(layout, /favicon\.ico\?v=3/);
  assert.match(layout, /favicon-16x16\.png\?v=3/);
  assert.match(layout, /favicon-32x32\.png\?v=3/);
  assert.match(layout, /favicon-48x48\.png\?v=3/);
  assert.match(layout, /brand\/slivadoc-favicon\.png\?v=3/);
  assert.match(layout, /apple-touch-icon\.png\?v=3/);
  assert.match(layout, /mstile-150x150\.png\?v=3/);
  assert.match(layout, /manifest: "\/manifest\.webmanifest"/);
  assert.match(manifest, /slivadoc-192\.png\?v=3/);
  assert.match(manifest, /slivadoc-512\.png\?v=3/);
  assert.match(manifest, /slivadoc-maskable-192\.png\?v=3/);
  assert.match(manifest, /slivadoc-maskable-512\.png\?v=3/);
  assert.match(svgFavicon, /<title>Slivadoc<\/title>/);
  assert.match(svgFavicon, /data:image\/png;base64/);
  assert.doesNotMatch(svgFavicon, /M22 19\.2727/);
  assert.match(layout, /<GoogleAnalytics \/>/);
  assert.match(analytics, /G-1HBZTWHBPN/);
  assert.match(analytics, /analytics_storage: "granted"/);
  assert.match(analytics, /ad_storage: "denied"/);
  assert.match(analytics, /allow_google_signals: false/);
  assert.match(analytics, /allow_ad_personalization_signals: false/);
  assert.match(analytics, /send_page_view: true/);
  assert.match(analytics, /googletagmanager\.com\/gtag\/js/);
  assert.doesNotMatch(analytics, /Tolak analitik|Izinkan analitik|localStorage|role="dialog"/);
  assert.doesNotMatch(styles, /\.analytics-consent/);
  assert.match(html, /Dari bisnis lokal menjadi bagian dari/);
  assert.match(html, /aplikasi POS petshop, klinik hewan, grooming/);
  assert.match(html, /Apakah Slivadoc menyediakan aplikasi POS untuk petshop dan klinik hewan/);
  assert.match(html, /brand\/slivadoc-logo\.png/);
  assert.match(html, /LanguageSwitcher/);
  assert.match(html, /Gabung ke ekosistem/);
  assert.match(html, /<b>38<\/b><small>Provinsi di Indonesia<\/small>/);
  assert.doesNotMatch(html, /Provinsi terjangkau/);
  assert.match(html, /Pet owner tetap menggunakan aplikasi khusus Pet Owner/);
  assert.match(html, /100% Gratis/);
  assert.match(html, /Semua partner terdaftar mendapatkan akses full gratis/);
  assert.match(categoryForm, /Tanpa biaya pendaftaran, onboarding, fitur, atau langganan/);
  assert.match(html, /Apakah bergabung dan menggunakan Slivadoc benar-benar gratis/);
  assert.match(html, /Chat WhatsApp Customer Support Slivadoc/);
  assert.match(html, /wa\.me\/6281977388341/);
  assert.match(html, /Partner Pengiriman/);
  assert.match(html, /Lion Parcel/);
  assert.match(html, /J&T Cargo/);
  assert.match(html, /SiCepat Express/);
  assert.match(html, /IDExpress/);
  assert.match(html, /Partner Pembayaran/);
  assert.match(html, /BatPay/);
  assert.match(html, /OCBC/);
  assert.match(html, /CIMB/);
  assert.match(html, /Mandiri/);
  assert.match(html, /partners\/lion-parcel\.svg/);
  assert.match(html, /partners\/jne\.svg/);
  assert.match(html, /partners\/jnt-cargo\.svg/);
  assert.match(html, /partners\/sicepat\.svg/);
  assert.match(html, /partners\/idexpress\.svg/);
  assert.match(html, /partners\/batpay\.webp/);
  assert.match(html, /partners\/ocbc\.png/);
  assert.match(html, /partners\/cimb\.svg/);
  assert.match(html, /partners\/mandiri\.png/);
  assert.doesNotMatch(html, /<strong>\{partner\.name\}<\/strong>/);
  assert.ok(partnerLogoAssets.every((asset) => asset.length > 2_000));
  assert.match(html, /Visi infrastruktur Slivadoc/);
  assert.doesNotMatch(html, /Ilustrasi menggambarkan rencana pengembangan infrastruktur Slivadoc/);
  assert.match(html, /slivadoc-warehouse\.webp/);
  assert.match(html, /slivadoc-ecosystem-hero\.webp/);
  assert.match(html, /The connected pet-care economy/);
  assert.match(html, /Satu pusat\.<br \/>Semua terhubung/);
  assert.match(html, /Ditemukan/);
  assert.match(html, /Dipenuhi/);
  assert.match(styles, /\.partner-network-section/);
  assert.match(styles, /\.warehouse-section/);
  assert.match(styles, /\.ecosystem-map-section/);
  assert.match(styles, /\.value-flow-section/);
  assert.match(styles, /Final blue-sky brand polish/);
  assert.match(styles, /\.partner-brand-logo-shell/);
  assert.ok(warehouseAsset.length > 50_000);
  assert.ok(ecosystemHeroAsset.length > 100_000);
  assert.match(categoryForm, /className="custom-select-trigger"/);
  assert.match(categoryForm, /role="listbox"/);
  assert.match(categoryForm, /Cari \$\{label\.toLowerCase\(\)\}/);
  assert.match(categoryForm, /className="check-control"/);
  assert.match(categoryForm, /key="partner-confirmation-step"/);
  assert.match(categoryForm, /className="submit-content" hidden=\{submitting\}/);
  assert.match(categoryForm, /className="submit-content notranslate" translate="no" hidden=\{!submitting\}/);
  assert.match(categoryForm, /trackEvent\("generate_lead"/);
  assert.match(categoryForm, /trackEvent\("form_step_complete"/);
  assert.doesNotMatch(categoryForm, /trackEvent\([^)]*(email|whatsapp|pic_name|legal_name)/s);
  assert.doesNotMatch(categoryForm, /submitting \? <><i className="spinner"/);
  assert.doesNotMatch(categoryForm, /<select name=/);
  assert.doesNotMatch(html, /akses dasar untuk memulai gratis/i);
  assert.doesNotMatch(html, /codex-preview/);
});
