import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { seoKeywords } from "../app/seo-keywords.mjs";

test("keeps the required Slivadoc Partners content", async () => {
  const html = await readFile(new URL("../app/partner-portal.tsx", import.meta.url), "utf8");
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  const robots = await readFile(new URL("../app/robots.ts", import.meta.url), "utf8");
  const sitemap = await readFile(new URL("../app/sitemap.ts", import.meta.url), "utf8");
  const analytics = await readFile(new URL("../app/google-analytics.tsx", import.meta.url), "utf8");
  const consent = await readFile(new URL("../app/analytics-consent.tsx", import.meta.url), "utf8");

  assert.match(layout, /Slivadoc Partners: Aplikasi POS Petshop & Klinik Hewan Gratis/);
  assert.match(layout, /metadataBase: new URL\(siteUrl\)/);
  assert.match(layout, /canonical: "\/"/);
  assert.match(layout, /keywords: seoKeywords/);
  assert.equal(seoKeywords.length, 500);
  assert.equal(new Set(seoKeywords).size, 500);
  assert.ok(seoKeywords.includes("aplikasi kasir petshop gratis"));
  assert.ok(seoKeywords.includes("aplikasi POS klinik hewan Indonesia"));
  assert.ok(seoKeywords.includes("aplikasi barcode petshop terintegrasi"));
  assert.match(layout, /"@type": "SoftwareApplication"/);
  assert.match(robots, /partners\.slivadoc\.com\/sitemap\.xml/);
  assert.match(sitemap, /https:\/\/partners\.slivadoc\.com/);
  assert.match(layout, /brand\/slivadoc-favicon\.png/);
  assert.match(layout, /<GoogleAnalytics \/>/);
  assert.match(analytics, /G-1HBZTWHBPN/);
  assert.match(analytics, /<AnalyticsConsent measurementId=\{measurementId\} \/>/);
  assert.match(consent, /analytics_storage: "granted"/);
  assert.match(consent, /ad_storage: "denied"/);
  assert.match(consent, /googletagmanager\.com\/gtag\/js/);
  assert.match(consent, /Tolak analitik/);
  assert.match(consent, /Izinkan analitik/);
  assert.match(html, /Bisnis pet care Anda layak/);
  assert.match(html, /aplikasi POS petshop, klinik hewan, grooming/);
  assert.match(html, /Apakah Slivadoc menyediakan aplikasi POS untuk petshop dan klinik hewan/);
  assert.match(html, /brand\/slivadoc-logo\.png/);
  assert.match(html, /LanguageSwitcher/);
  assert.match(html, /Daftar jadi partner/);
  assert.match(html, /<b>38<\/b><small>Provinsi di Indonesia<\/small>/);
  assert.doesNotMatch(html, /Provinsi terjangkau/);
  assert.match(html, /Pet owner tetap menggunakan aplikasi khusus Pet Owner/);
  assert.match(html, /100% Gratis/);
  assert.match(html, /Semua partner terdaftar mendapatkan akses full gratis/);
  assert.match(html, /Tanpa biaya pendaftaran, onboarding, fitur, atau langganan/);
  assert.match(html, /Apakah bergabung dan menggunakan Slivadoc benar-benar gratis/);
  assert.match(html, /Chat WhatsApp Customer Support Slivadoc/);
  assert.match(html, /wa\.me\/6281977388341/);
  assert.match(html, /className="custom-select-trigger"/);
  assert.match(html, /role="listbox"/);
  assert.match(html, /Cari \$\{label\.toLowerCase\(\)\}/);
  assert.match(html, /className="check-control"/);
  assert.match(html, /key="partner-confirmation-step"/);
  assert.match(html, /className="submit-content" hidden=\{submitting\}/);
  assert.match(html, /className="submit-content notranslate" translate="no" hidden=\{!submitting\}/);
  assert.match(html, /trackEvent\("generate_lead"/);
  assert.match(html, /trackEvent\("form_step_complete"/);
  assert.doesNotMatch(html, /trackEvent\([^)]*(email|whatsapp|pic_name|legal_name)/s);
  assert.doesNotMatch(html, /submitting \? <><i className="spinner"/);
  assert.doesNotMatch(html, /<select name=/);
  assert.doesNotMatch(html, /akses dasar untuk memulai gratis/i);
  assert.doesNotMatch(html, /codex-preview/);
});
