import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { seoKeywords } from "../app/seo-keywords.mjs";

test("keeps the required Slivadoc Partners content", async () => {
  const html = await readFile(new URL("../app/partner-portal.tsx", import.meta.url), "utf8");
  const layout = await readFile(new URL("../app/layout.tsx", import.meta.url), "utf8");
  const manifest = await readFile(new URL("../app/manifest.ts", import.meta.url), "utf8");
  const svgFavicon = await readFile(new URL("../public/favicon.svg", import.meta.url), "utf8");
  const robots = await readFile(new URL("../app/robots.ts", import.meta.url), "utf8");
  const sitemap = await readFile(new URL("../app/sitemap.ts", import.meta.url), "utf8");
  const analytics = await readFile(new URL("../app/google-analytics.tsx", import.meta.url), "utf8");
  const consent = await readFile(new URL("../app/analytics-consent.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const warehouseAsset = await readFile(new URL("../public/brand/slivadoc-warehouse.webp", import.meta.url));
  const ecosystemHeroAsset = await readFile(new URL("../public/brand/slivadoc-ecosystem-hero.webp", import.meta.url));

  assert.match(layout, /Slivadoc Partners: Aplikasi POS Petshop & Klinik Hewan Gratis/);
  assert.match(layout, /metadataBase: new URL\(siteUrl\)/);
  assert.match(layout, /canonical: "\/"/);
  assert.match(layout, /keywords: seoKeywords/);
  assert.match(layout, /summary_large_image/);
  assert.match(layout, /slivadoc-ecosystem-hero\.webp/);
  assert.equal(seoKeywords.length, 500);
  assert.equal(new Set(seoKeywords).size, 500);
  assert.ok(seoKeywords.includes("aplikasi kasir petshop gratis"));
  assert.ok(seoKeywords.includes("aplikasi POS klinik hewan Indonesia"));
  assert.ok(seoKeywords.includes("aplikasi barcode petshop terintegrasi"));
  assert.match(layout, /"@type": "SoftwareApplication"/);
  assert.match(robots, /partners\.slivadoc\.com\/sitemap\.xml/);
  assert.match(sitemap, /https:\/\/partners\.slivadoc\.com/);
  assert.match(layout, /favicon\.ico\?v=3/);
  assert.match(layout, /favicon-16x16\.png\?v=3/);
  assert.match(layout, /favicon-32x32\.png\?v=3/);
  assert.match(layout, /favicon-48x48\.png\?v=3/);
  assert.match(layout, /brand\/slivadoc-favicon\.png\?v=3/);
  assert.match(layout, /apple-touch-icon\.png\?v=3/);
  assert.match(layout, /mstile-150x150\.png\?v=3/);
  assert.match(layout, /manifest: "\/manifest\.webmanifest"/);
  assert.match(manifest, /slivadoc-192\.png\?v=3/);
  assert.match(manifest, /slivadoc-512\.png\?v=3/);
  assert.match(manifest, /slivadoc-maskable-192\.png\?v=3/);
  assert.match(manifest, /slivadoc-maskable-512\.png\?v=3/);
  assert.match(svgFavicon, /<title>Slivadoc<\/title>/);
  assert.match(svgFavicon, /data:image\/png;base64/);
  assert.doesNotMatch(svgFavicon, /M22 19\.2727/);
  assert.match(layout, /<GoogleAnalytics \/>/);
  assert.match(analytics, /G-1HBZTWHBPN/);
  assert.match(analytics, /<AnalyticsConsent measurementId=\{measurementId\} \/>/);
  assert.match(consent, /analytics_storage: "granted"/);
  assert.match(consent, /ad_storage: "denied"/);
  assert.match(consent, /googletagmanager\.com\/gtag\/js/);
  assert.match(consent, /Tolak analitik/);
  assert.match(consent, /Izinkan analitik/);
  assert.match(html, /Dari bisnis lokal menjadi bagian dari/);
  assert.match(html, /aplikasi POS petshop, klinik hewan, grooming/);
  assert.match(html, /Apakah Slivadoc menyediakan aplikasi POS untuk petshop dan klinik hewan/);
  assert.match(html, /brand\/slivadoc-logo\.png/);
  assert.match(html, /LanguageSwitcher/);
  assert.match(html, /Gabung ke ekosistem/);
  assert.match(html, /<b>38<\/b><small>Provinsi di Indonesia<\/small>/);
  assert.doesNotMatch(html, /Provinsi terjangkau/);
  assert.match(html, /Pet owner tetap menggunakan aplikasi khusus Pet Owner/);
  assert.match(html, /100% Gratis/);
  assert.match(html, /Semua partner terdaftar mendapatkan akses full gratis/);
  assert.match(html, /Tanpa biaya pendaftaran, onboarding, fitur, atau langganan/);
  assert.match(html, /Apakah bergabung dan menggunakan Slivadoc benar-benar gratis/);
  assert.match(html, /Chat WhatsApp Customer Support Slivadoc/);
  assert.match(html, /wa\.me\/6281977388341/);
  assert.match(html, /Partner Pengiriman/);
  assert.match(html, /Lion Parcel/);
  assert.match(html, /J&T Cargo/);
  assert.match(html, /SiCepat Express/);
  assert.match(html, /IDExpress/);
  assert.match(html, /Partner Pembayaran/);
  assert.match(html, /BatPay/);
  assert.match(html, /OCBC/);
  assert.match(html, /CIMB/);
  assert.match(html, /Mandiri/);
  assert.match(html, /Visi infrastruktur Slivadoc/);
  assert.match(html, /slivadoc-warehouse\.webp/);
  assert.match(html, /slivadoc-ecosystem-hero\.webp/);
  assert.match(html, /The connected pet-care economy/);
  assert.match(html, /Satu pusat\.<br \/>Semua terhubung/);
  assert.match(html, /Ditemukan/);
  assert.match(html, /Dipenuhi/);
  assert.match(styles, /\.partner-network-section/);
  assert.match(styles, /\.warehouse-section/);
  assert.match(styles, /\.ecosystem-map-section/);
  assert.match(styles, /\.value-flow-section/);
  assert.ok(warehouseAsset.length > 50_000);
  assert.ok(ecosystemHeroAsset.length > 100_000);
  assert.match(html, /className="custom-select-trigger"/);
  assert.match(html, /role="listbox"/);
  assert.match(html, /Cari \$\{label\.toLowerCase\(\)\}/);
  assert.match(html, /className="check-control"/);
  assert.match(html, /key="partner-confirmation-step"/);
  assert.match(html, /className="submit-content" hidden=\{submitting\}/);
  assert.match(html, /className="submit-content notranslate" translate="no" hidden=\{!submitting\}/);
  assert.match(html, /trackEvent\("generate_lead"/);
  assert.match(html, /trackEvent\("form_step_complete"/);
  assert.doesNotMatch(html, /trackEvent\([^)]*(email|whatsapp|pic_name|legal_name)/s);
  assert.doesNotMatch(html, /submitting \? <><i className="spinner"/);
  assert.doesNotMatch(html, /<select name=/);
  assert.doesNotMatch(html, /akses dasar untuk memulai gratis/i);
  assert.doesNotMatch(html, /codex-preview/);
});
