"use client";

import { FormEvent, useState } from "react";

const partnerTypes = [
  { code: "01", title: "Brand Commerce", text: "Distribusikan produk ke jaringan pet shop dan tampil langsung di katalog pet owner.", metric: "320+ outlet", accent: "from-sky-500 to-cyan-400" },
  { code: "02", title: "Data & Insight", text: "Pahami tren kategori, perilaku pelanggan, dan performa produk tanpa membuka data pribadi.", metric: "38 provinsi", accent: "from-violet-500 to-fuchsia-400" },
  { code: "03", title: "Campaign Studio", text: "Jalankan edukasi, activation, sampling, voucher, dan kolaborasi komunitas terukur.", metric: "184K pawrents", accent: "from-amber-500 to-orange-400" },
];

const campaigns = [
  { title: "Healthy Coat Month", brand: "NutriPaw", reach: "82.400", conversion: "8,7%", status: "Aktif", color: "bg-sky-500" },
  { title: "Adopt with Love", brand: "PawKind", reach: "54.120", conversion: "11,2%", status: "Aktif", color: "bg-violet-500" },
  { title: "Dental Care Week", brand: "VetSmile", reach: "37.890", conversion: "6,4%", status: "Terjadwal", color: "bg-amber-500" },
];

export default function PartnerPortal() {
  const [modal, setModal] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [active, setActive] = useState("Overview");
  const [period, setPeriod] = useState("30 hari");

  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setSubmitted(true);
  };

  return (
    <main className="min-h-screen overflow-hidden bg-[#071b2d] text-white">
      <header className="relative z-20 border-b border-white/10 bg-[#071b2d]/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1240px] items-center px-5"><a href="#home" className="flex items-center gap-3 text-xl font-extrabold tracking-tight"><span className="grid size-10 place-items-center rounded-2xl bg-gradient-to-br from-sky-400 to-blue-600">S</span><span>sliva<span className="text-sky-400">doc</span><small className="ml-2 align-middle text-[8px] font-bold uppercase tracking-[.2em] text-slate-400">Partners</small></span></a><nav className="ml-auto hidden items-center gap-7 md:flex">{["Overview","Solutions","Insights","Campaigns"].map((item) => <a onClick={() => setActive(item)} className={`text-xs font-semibold transition hover:text-white ${active === item ? "text-sky-400" : "text-slate-400"}`} href={`#${item.toLowerCase()}`} key={item}>{item}</a>)}</nav><button onClick={() => setModal(true)} className="ml-5 rounded-xl bg-white px-4 py-3 text-[10px] font-extrabold text-[#0b2338] transition hover:-translate-y-0.5">Ajukan partnership</button></div></header>

      <section id="home" className="relative"><div className="absolute -right-40 -top-24 size-[620px] rounded-full bg-sky-500/10 blur-3xl"/><div className="absolute left-1/3 top-64 size-80 rounded-full bg-violet-500/10 blur-3xl"/><div className="relative mx-auto grid min-h-[640px] max-w-[1240px] items-center gap-12 px-5 py-20 lg:grid-cols-[1.05fr_.95fr]">
        <div><span className="inline-flex items-center gap-2 rounded-full border border-sky-400/20 bg-sky-400/10 px-3 py-2 text-[9px] font-bold uppercase tracking-[.16em] text-sky-300"><i className="size-1.5 rounded-full bg-sky-400"/> Indonesia&apos;s pet ecosystem network</span><h1 className="mt-6 max-w-2xl text-5xl font-black leading-[1.02] tracking-[-.055em] sm:text-6xl">Tumbuh bersama ekosistem pet care yang <span className="bg-gradient-to-r from-sky-300 to-cyan-200 bg-clip-text text-transparent">lebih terhubung.</span></h1><p className="mt-6 max-w-xl text-sm leading-7 text-slate-300">Slivadoc menghubungkan brand dengan pet owner, dokter hewan, klinik, pet shop, komunitas, dan data pasar dalam satu platform kolaborasi.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => setModal(true)} className="rounded-xl bg-sky-500 px-6 py-4 text-xs font-extrabold shadow-2xl shadow-sky-900">Mulai berkolaborasi →</button><a href="#insights" className="rounded-xl border border-white/15 bg-white/5 px-6 py-4 text-xs font-bold text-slate-200">Lihat partner insights</a></div><div className="mt-10 flex flex-wrap gap-8">{[["184K+","Pet owner"],["320+","Business"],["38","Provinsi"]].map(([value,label]) => <div key={label}><strong className="block text-xl">{value}</strong><span className="text-[9px] uppercase tracking-widest text-slate-500">{label}</span></div>)}</div></div>

        <div className="relative"><div className="absolute -inset-5 rounded-[36px] bg-gradient-to-br from-sky-500/20 to-violet-500/10 blur-xl"/><div className="relative rounded-[28px] border border-white/10 bg-white/[.07] p-5 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-[8px] font-bold uppercase tracking-[.18em] text-slate-400">Partner intelligence</p><h2 className="mt-1 text-sm font-bold">Market pulse · Indonesia</h2></div><select value={period} onChange={(e) => setPeriod(e.target.value)} className="rounded-lg border border-white/10 bg-white/10 px-3 py-2 text-[9px] outline-none"><option className="text-slate-900">30 hari</option><option className="text-slate-900">90 hari</option></select></div><div className="mt-4 grid grid-cols-2 gap-3">{[["Category growth","+24,8%","↗"],["Active buyers","41.820","♙"],["Campaign ROAS","4,7x","◇"],["Store coverage","87 kota","⌖"]].map(([label,value,icon]) => <article className="rounded-2xl border border-white/10 bg-[#0b2a43]/80 p-4" key={label}><span className="text-sky-400">{icon}</span><p className="mt-5 text-[9px] text-slate-400">{label}</p><strong className="mt-1 block text-lg">{value}</strong></article>)}</div><div className="mt-3 rounded-2xl bg-white p-4 text-[#10283e]"><div className="flex items-center justify-between"><div><p className="text-[8px] font-bold uppercase tracking-widest text-slate-400">Fastest growing</p><h3 className="mt-1 text-xs font-bold">Functional nutrition</h3></div><span className="rounded-lg bg-emerald-50 px-2 py-1 text-[9px] font-bold text-emerald-600">+31,2%</span></div><div className="mt-5 flex h-20 items-end gap-2">{[36,45,39,55,52,68,61,79,73,91].map((height,index) => <span key={index} className="flex-1 rounded-t bg-gradient-to-t from-sky-500 to-cyan-300" style={{height:`${height}%`}}/>)}</div></div></div></div>
      </div></section>

      <section id="solutions" className="bg-[#f5f8fb] py-24 text-[#10263d]"><div className="mx-auto max-w-[1240px] px-5"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-sky-600">Partnership solutions</p><div className="mt-3 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="max-w-xl text-3xl font-black tracking-tight sm:text-4xl">Satu pintu untuk bertumbuh di industri pet care.</h2><p className="max-w-md text-xs leading-6 text-slate-500">Mulai dari distribusi hingga activation, semua program dibangun dengan target dan metrik yang transparan.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{partnerTypes.map((item) => <article key={item.code} className="group rounded-3xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:shadow-2xl hover:shadow-slate-200"><div className="flex items-center justify-between"><span className={`grid size-11 place-items-center rounded-2xl bg-gradient-to-br text-xs font-black text-white ${item.accent}`}>{item.code}</span><b className="text-[9px] text-sky-600">{item.metric}</b></div><h3 className="mt-8 text-lg font-extrabold">{item.title}</h3><p className="mt-3 text-xs leading-6 text-slate-500">{item.text}</p><button onClick={() => setModal(true)} className="mt-7 text-[10px] font-extrabold text-sky-600">Pelajari solusi →</button></article>)}</div></div></section>

      <section id="insights" className="bg-white py-24 text-[#10263d]"><div className="mx-auto grid max-w-[1240px] gap-10 px-5 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-violet-600">Live insight</p><h2 className="mt-3 text-3xl font-black tracking-tight">Keputusan brand berbasis sinyal nyata.</h2><p className="mt-4 text-xs leading-6 text-slate-500">Lihat perubahan demand berdasarkan kategori, wilayah, kanal, dan profil pet tanpa mengorbankan privasi pet owner.</p><div className="mt-8 grid grid-cols-2 gap-3">{[["#1","Cat nutrition"],["#2","Preventive care"],["#3","Smart accessories"],["#4","Pet travel"]].map(([rank,label]) => <div className="rounded-2xl bg-slate-50 p-4" key={rank}><span className="text-[9px] font-bold text-violet-600">{rank}</span><strong className="mt-2 block text-[11px]">{label}</strong></div>)}</div></div><div className="rounded-3xl bg-[#0c2740] p-6 text-white"><div className="flex justify-between"><div><p className="text-[8px] uppercase tracking-widest text-slate-400">Demand index</p><h3 className="mt-1 text-sm font-bold">Jabodetabek · Agustus</h3></div><span className="text-[9px] text-emerald-300">● Live</span></div><div className="mt-8 space-y-5">{[["Premium food",88,"+26%"],["Health supplements",72,"+18%"],["Grooming care",64,"+12%"],["Travel gear",51,"+9%"]].map(([label,value,growth]) => <div key={String(label)}><div className="mb-2 flex justify-between text-[9px]"><span>{label}</span><b className="text-emerald-300">{growth}</b></div><div className="h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-sky-500 to-cyan-300" style={{width:`${value}%`}}/></div></div>)}</div></div></div></section>

      <section id="campaigns" className="bg-[#eef4f8] py-24 text-[#10263d]"><div className="mx-auto max-w-[1240px] px-5"><div className="flex items-end justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-sky-600">Campaign studio</p><h2 className="mt-3 text-3xl font-black tracking-tight">Program yang sedang tumbuh.</h2></div><button onClick={() => setModal(true)} className="hidden rounded-xl bg-[#102a43] px-5 py-3 text-[10px] font-bold text-white sm:block">Buat campaign</button></div><div className="mt-9 grid gap-4 lg:grid-cols-3">{campaigns.map((item) => <article className="rounded-3xl border border-slate-200 bg-white p-5" key={item.title}><div className="flex items-center justify-between"><span className={`h-1.5 w-16 rounded-full ${item.color}`}/><span className="rounded-full bg-emerald-50 px-2 py-1 text-[8px] font-bold text-emerald-600">{item.status}</span></div><p className="mt-6 text-[9px] font-bold uppercase tracking-widest text-slate-400">{item.brand}</p><h3 className="mt-2 text-base font-extrabold">{item.title}</h3><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><small className="block text-[8px] text-slate-400">Reach</small><b className="mt-1 block text-xs">{item.reach}</b></div><div className="rounded-xl bg-slate-50 p-3"><small className="block text-[8px] text-slate-400">Conversion</small><b className="mt-1 block text-xs">{item.conversion}</b></div></div></article>)}</div></div></section>

      <footer className="border-t border-white/10"><div className="mx-auto flex max-w-[1240px] flex-col gap-5 px-5 py-10 sm:flex-row sm:items-center sm:justify-between"><span className="font-extrabold">sliva<span className="text-sky-400">doc</span> partners</span><p className="text-[10px] text-slate-500">Kolaborasi untuk masa depan pet care Indonesia.</p><button onClick={() => setModal(true)} className="text-left text-[10px] font-bold text-sky-400">partner@slivadoc.com →</button></div></footer>

      {modal && <div className="fixed inset-0 z-50 grid place-items-end bg-[#061421]/75 p-0 backdrop-blur-sm sm:place-items-center sm:p-5" onMouseDown={() => setModal(false)}><section onMouseDown={(e) => e.stopPropagation()} className="w-full max-w-lg rounded-t-3xl bg-white p-6 text-[#10263d] shadow-2xl sm:rounded-3xl"><div className="flex items-start justify-between"><div><p className="text-[9px] font-extrabold uppercase tracking-widest text-sky-600">Partner with Slivadoc</p><h2 className="mt-2 text-2xl font-black">{submitted ? "Terima kasih!" : "Mari mulai percakapan."}</h2></div><button aria-label="Tutup" onClick={() => setModal(false)} className="grid size-9 place-items-center rounded-full bg-slate-100 text-xl">×</button></div>{submitted ? <div className="py-12 text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-emerald-50 text-2xl text-emerald-600">✓</span><p className="mt-5 text-sm font-bold">Proposal awal sudah diterima.</p><p className="mt-2 text-xs text-slate-500">Tim partnership akan menghubungi Anda dalam 1–2 hari kerja.</p><button onClick={() => {setSubmitted(false);setModal(false)}} className="mt-6 rounded-xl bg-[#102a43] px-5 py-3 text-xs font-bold text-white">Selesai</button></div> : <form onSubmit={submit} className="mt-6 grid gap-4"><label className="text-[10px] font-bold">Nama brand<input required className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-xs font-normal outline-none focus:border-sky-400" placeholder="Contoh: NutriPaw Indonesia"/></label><label className="text-[10px] font-bold">Email bisnis<input required type="email" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-xs font-normal outline-none focus:border-sky-400" placeholder="nama@brand.com"/></label><label className="text-[10px] font-bold">Fokus kolaborasi<select className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-xs font-normal outline-none"><option>Distribusi produk</option><option>Campaign & activation</option><option>Data & market insight</option><option>Program CSR</option></select></label><button className="mt-2 rounded-xl bg-sky-500 py-4 text-xs font-extrabold text-white">Kirim proposal awal →</button></form>}</section></div>}
    </main>
  );
}
