export const partnershipCategories = [
  { value: "veterinary_clinic", slug: "klinik-hewan", label: "Klinik & RS Hewan", description: "Booking, rekam medis, POS, dan stok", icon: "plus", query: "kemitraan klinik hewan", intro: "Hubungkan jadwal dokter, layanan klinis, rekam medis, kasir, dan kebutuhan stok dalam perjalanan perawatan pet owner.", benefits: ["Kelola reservasi dan antrean layanan klinik", "Hubungkan catatan medis dengan transaksi", "Siapkan operasional cabang dan inventori"], preparation: "Siapkan identitas klinik, izin praktik terkait, daftar layanan, jadwal dokter, dan area operasional." },
  { value: "independent_veterinarian", slug: "dokter-hewan", label: "Dokter Hewan", description: "Konsultasi online dan home visit", icon: "stethoscope", query: "kemitraan dokter hewan", intro: "Daftarkan praktik dokter hewan independen untuk konsultasi, layanan kunjungan, dan pengalaman perawatan yang terhubung dengan pet owner.", benefits: ["Tampilkan keahlian dan ketersediaan konsultasi", "Atur layanan online atau kunjungan", "Bantu pet owner menemukan bantuan klinis"], preparation: "Siapkan identitas profesional, dokumen izin praktik yang relevan, layanan, dan area kunjungan." },
  { value: "pet_shop", slug: "petshop", label: "Pet Shop", description: "Marketplace, inventori, dan member", icon: "bag", query: "kemitraan petshop", intro: "Perkenalkan pet shop Anda kepada pet owner sambil menata katalog, kasir, stok, pelanggan, dan pemenuhan pesanan.", benefits: ["Kelola penjualan dan stok produk pet", "Jangkau pelanggan melalui katalog dan marketplace", "Rapikan transaksi, member, dan laporan"], preparation: "Siapkan profil toko, daftar produk utama, lokasi, cakupan pengiriman, dan dokumen usaha." },
  { value: "pet_grooming", slug: "grooming-hewan", label: "Grooming & Salon", description: "Booking, groomer, dan paket layanan", icon: "sparkle", query: "kemitraan grooming hewan", intro: "Buka pemesanan grooming yang jelas bagi pet owner dan kelola groomer, paket perawatan, jadwal, serta transaksi harian.", benefits: ["Tawarkan paket grooming dengan jadwal tersedia", "Kelola tugas groomer dan histori layanan", "Terima pemesanan dengan informasi pet"], preparation: "Siapkan paket grooming, harga, kapasitas jadwal, lokasi, dan standar penanganan pet." },
  { value: "pet_hotel_daycare", slug: "pet-hotel-daycare", label: "Pet Hotel & Daycare", description: "Kamar, reservasi, dan catatan perawatan", icon: "home", query: "kemitraan pet hotel daycare", intro: "Kelola kapasitas kamar, reservasi menginap atau daycare, kebutuhan khusus pet, dan catatan perawatan selama dititipkan.", benefits: ["Tampilkan kamar dan slot penitipan", "Catat kebutuhan makan serta aktivitas pet", "Pantau pemesanan dan ketersediaan"], preparation: "Siapkan kapasitas, tipe kamar, tarif, persyaratan vaksin, dan kebijakan penitipan." },
  { value: "home_service", slug: "home-service-hewan", label: "Home Service", description: "Penugasan, kunjungan, dan bukti layanan", icon: "route", query: "kemitraan home service hewan", intro: "Bawa layanan pet care ke rumah dengan cakupan wilayah, jadwal kunjungan, penugasan tim, dan pembaruan status yang tertata.", benefits: ["Atur cakupan dan jadwal kunjungan", "Tugaskan petugas untuk layanan lapangan", "Catat penyelesaian dan bukti layanan"], preparation: "Siapkan jenis layanan rumah, tenaga lapangan, area cakupan, jam kerja, dan prosedur kunjungan." },
  { value: "pet_academy_trainer", slug: "pet-academy", label: "Pet Academy", description: "Kelas, pendaftaran, dan progres", icon: "award", query: "kemitraan pet academy", intro: "Daftarkan akademi atau badan usaha pelatihan pet untuk mengelola program, kelas, jadwal pengajar, peserta, dan progres pembelajaran.", benefits: ["Susun program dan jadwal kelas", "Kelola pendaftaran serta kapasitas", "Pantau progres peserta dan pet"], preparation: "Siapkan profil lembaga, program kelas, tenaga pengajar, fasilitas, dan dokumen usaha." },
  { value: "pet_pharmacy", slug: "apotek-hewan", label: "Apotek Pet", description: "Produk kesehatan, stok, dan pesanan", icon: "pill", query: "kemitraan apotek hewan", intro: "Hubungkan apotek pet dengan kebutuhan produk kesehatan hewan, katalog, stok, pesanan, dan alur pemenuhan yang sesuai kewenangan usaha.", benefits: ["Kelola katalog dan ketersediaan produk", "Pantau stok dan pesanan", "Perjelas informasi produk bagi pet owner"], preparation: "Siapkan profil usaha, izin yang relevan, kategori produk, dan proses penanganan pesanan." },
  { value: "diagnostic_laboratory", slug: "laboratorium-hewan", label: "Laboratorium", description: "Pemeriksaan, hasil, dan rekam medis", icon: "lab", query: "kemitraan laboratorium hewan", intro: "Permudah kolaborasi pemeriksaan diagnostik hewan dengan klinik dan dokter melalui informasi layanan, permintaan tes, dan hasil.", benefits: ["Jelaskan jenis pemeriksaan yang tersedia", "Kelola alur permintaan dan hasil lab", "Dukung tindak lanjut perawatan klinis"], preparation: "Siapkan daftar tes, cakupan layanan, waktu hasil, dokumen operasional, dan kontak penanggung jawab." },
  { value: "shelter_rescue", slug: "shelter-rescue", label: "Shelter & Rescue", description: "Adopsi, moderasi, dan penyaringan", icon: "heart", query: "kemitraan shelter hewan", intro: "Perkenalkan shelter atau kegiatan rescue untuk membantu proses adopsi, edukasi, dan penelusuran calon adopter yang lebih tertata.", benefits: ["Kelola profil pet yang siap diadopsi", "Catat proses penyaringan calon adopter", "Hubungkan komunitas dengan kebutuhan rescue"], preparation: "Siapkan profil organisasi, prosedur adopsi, area kegiatan, dan kontak pengelola." },
  { value: "pet_community", slug: "komunitas-pet", label: "Komunitas Pet", description: "Komunitas, PetHub, dan kampanye", icon: "users", query: "kemitraan komunitas hewan", intro: "Bangun kolaborasi komunitas pet melalui kegiatan, konten edukasi, kampanye, dan percakapan antarpet owner.", benefits: ["Perkenalkan komunitas dan kegiatannya", "Rancang kampanye edukasi bersama", "Hubungkan anggota dengan ekosistem pet care"], preparation: "Siapkan profil komunitas, fokus kegiatan, pengurus, kanal publik, dan rencana kolaborasi." },
  { value: "pet_event_organizer", slug: "event-pet", label: "Pet Event", description: "Acara, tiket, dan analitik", icon: "calendar", query: "kemitraan event hewan", intro: "Daftarkan penyelenggara event pet untuk mempromosikan acara, mengelola tiket, peserta, dan peluang kerja sama ekosistem.", benefits: ["Publikasikan jadwal dan detail event", "Kelola pendaftaran atau tiket", "Pantau minat peserta dan kampanye"], preparation: "Siapkan profil penyelenggara, jenis acara, lokasi, kapasitas, dan kalender event." },
  { value: "pet_friendly_venue", slug: "tempat-pet-friendly", label: "Pet-Friendly Venue", description: "PetSpot, penemuan tempat, dan kunjungan", icon: "pin", query: "kemitraan tempat pet friendly", intro: "Bantu pet owner menemukan tempat yang menerima pet dengan aturan kunjungan, fasilitas, reservasi, dan pengalaman yang jelas.", benefits: ["Tampilkan fasilitas dan aturan pet", "Buka peluang reservasi atau kunjungan", "Tingkatkan penemuan tempat melalui PetSpot"], preparation: "Siapkan jenis venue, alamat, fasilitas, kapasitas, jam buka, dan kebijakan membawa pet." },
  { value: "pet_insurance", slug: "asuransi-hewan", label: "Asuransi Pet", description: "Perlindungan dan penawaran partner", icon: "shield", query: "kemitraan asuransi hewan", intro: "Jajaki perlindungan pet bersama Slivadoc melalui informasi produk yang jelas dan perjalanan pembelian yang sesuai proses verifikasi.", benefits: ["Perkenalkan cakupan dan pengecualian produk", "Susun penawaran yang relevan bagi pet owner", "Hubungkan layanan perlindungan dengan perawatan"], preparation: "Siapkan profil perusahaan, perizinan, ringkasan produk, cakupan, dan kontak kemitraan." },
  { value: "brand_manufacturer", slug: "brand-produk-hewan", label: "Brand & Produsen", description: "Perdagangan, kampanye, dan wawasan", icon: "cube", query: "kemitraan brand produk hewan", intro: "Bangun distribusi produk pet bersama ekosistem toko dan pet owner sambil menyiapkan katalog, kampanye, dan kerja sama komersial.", benefits: ["Tampilkan katalog dan informasi brand", "Jajaki kampanye bersama partner", "Pantau permintaan dan jangkauan produk"], preparation: "Siapkan profil brand, kategori produk, dokumen produk, katalog, serta cakupan distribusi." },
  { value: "distributor_supplier", slug: "distributor-supplier", label: "Distributor & Supplier", description: "Pasokan, purchase order, dan cakupan", icon: "truck", query: "kemitraan distributor pet", intro: "Hubungkan pasokan kebutuhan pet care dengan brand, toko, dan mitra melalui katalog grosir, purchase order, dan jaringan distribusi.", benefits: ["Perjelas kategori serta wilayah pasokan", "Kelola kebutuhan purchase order", "Bangun relasi dengan mitra penjualan"], preparation: "Siapkan katalog pasokan, wilayah distribusi, persyaratan pemesanan, dan dokumen usaha." },
  { value: "logistics_pet_transport", slug: "logistik-pet", label: "Logistik & Transport", description: "Pengiriman, perjalanan pet, dan pelacakan", icon: "send", query: "kemitraan logistik hewan", intro: "Dukung pengiriman produk atau transportasi pet dengan cakupan rute, penjadwalan, pelacakan, dan standar layanan yang sesuai.", benefits: ["Petakan area dan jenis pengiriman", "Hubungkan status pengiriman dengan pesanan", "Jelaskan standar transportasi pet"], preparation: "Siapkan cakupan rute, jenis armada, SLA, kebijakan pengiriman, dan dokumen operasional." },
  { value: "government_association", slug: "instansi-asosiasi", label: "Instansi & Asosiasi", description: "Standar, edukasi, dan program", icon: "building", query: "kemitraan asosiasi hewan", intro: "Buka kerja sama edukasi, standar profesi, dan program publik bersama asosiasi atau instansi yang bergerak di ekosistem hewan.", benefits: ["Susun program edukasi bersama", "Perjelas standar dan ruang lingkup kerja sama", "Hubungkan organisasi dengan pelaku ekosistem"], preparation: "Siapkan profil lembaga, mandat atau kegiatan, penanggung jawab, dan usulan program." },
] as const;

export type PartnershipCategory = (typeof partnershipCategories)[number];
export const partnershipCategoryPath = (slug: string) => `/kemitraan/${slug}`;
export const findPartnershipCategory = (slug: string): PartnershipCategory | undefined => partnershipCategories.find((item) => item.slug === slug);
